version: "3.9"
services:
  app:
    build: .
    image: chatbot-whatsapp:v1.0.0-ALPHA
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production